### ISSUE TITLE
'NoneType' object is not iterable in translate_shell.translators.online.google module

### ISSUE THREAD

**Issue by sidb999** [Freed-Wu/translate-shell#33]
https://github.com/Freed-Wu/translate-shell/blob/b24592e3a080f770ceafc2726407513414d03578/src/translate_shell/translators/online/google.py#L150

Second index of the list "x" could contain None. That raises TypeError: 'type' object is not iterable.

STR:
`from translate_shell.translate import translate`
`translator = translate(
                    text="sample \nstring\n\n",
                    target_lang="ru",
                    source_lang="en"
            )`

Fix:
https://github.com/Freed-Wu/translate-shell/pull/32

**Comment by Freed-Wu** [comment]
Fixed by #32. Thanks!
