### ISSUE TITLE
square in terminal

### ISSUE THREAD

**Issue by fieri** [Freed-Wu/translate-shell#4]
![image](https://user-images.githubusercontent.com/32774617/209548426-a6d644a9-120f-4713-a4c1-2df8759bd685.png)

**Comment by Freed-Wu** [comment]
Can you try <https://www.nerdfonts.com/>?

**Comment by Freed-Wu** [comment]
@fieri

**Comment by Freed-Wu** [comment]
Have you installed [extras requires (e.g. color)](https://translate-shell.readthedocs.io/en/latest/resources/requirements.html#color)?
